apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: crossplane-contrib-provider-helm
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-helm:v0.15.0
  packagePullPolicy: IfNotPresent
  revisionActivationPolicy: Automatic
  revisionHistoryLimit: 1
  # We keep skipDependencyResolution disabled to work around a bug that
  # prevents configuration dependencies from resolving.
  # See https://github.com/crossplane/crossplane/issues/4588.
  skipDependencyResolution: false
