apiVersion: spaces.upbound.io/v1alpha1
kind: ControlPlane
metadata:
  name: ctp-dev
spec:
  source:
    git:
      url: https://github.com/cwilhit/spaces-reference-arch
      auth:
        type: None
      path: /controlplanes/ctp-dev/
      pullInterval: 15s
      ref:
        branch: main
  writeConnectionSecretToRef:
    name: kubeconfig-ctp-dev
    namespace: default
