apiVersion: meta.mxp.upbound.io/v1alpha1
kind: ControlPlaneSource
metadata:
  name: controlplane-dev
  annotations:
    meta.upbound.io/company: Acme Inc.
spec:
  rootPath: /
  # (Future) Pull secrets from external sources like Vault.
  # externalResources:
  #   - source:
  #       type: Vault
  #       vault:
  #         url: https://local.acme.org/vault/pull-secret
  #     type: Secret
  #     secret:
  #       metadata:
  #         name: internal-pull-secret
  #         namespace: upbound-system